import type { Metadata, Viewport } from "next";
import { Big_Shoulders, Courier_Prime, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";

// Dimuat via next/font/google agar self-hosted (tanpa request ke fonts.googleapis.com
// saat runtime) dan disambungkan ke --font-display/--font-ui/--font-mono di globals.css.
//
// Google Fonts sudah menggabungkan keluarga "Big Shoulders Display" (dipakai di
// mock-up docs/desain/*.html) ke dalam variable font "Big Shoulders" — next/font/google
// tidak lagi mengekspor "Big_Shoulders_Display" secara terpisah. Bobot 800 di keluarga
// gabungan ini setara secara visual dengan potongan "Display" lama.
const bigShouldersDisplay = Big_Shoulders({
  variable: "--font-big-shoulders-display",
  subsets: ["latin"],
  weight: ["800"],
});

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

const courierPrime = Courier_Prime({
  variable: "--font-courier-prime",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// viewportFit "cover" mengizinkan konten merender edge-to-edge di balik notch/home
// indicator (dibutuhkan untuk layar kamera/AR full-bleed nanti, Dokumen 03 §4.1) —
// tanpa ini, env(safe-area-inset-*) yang dipakai di padding header/penutup halaman
// selalu bernilai 0 karena browser sudah otomatis menahan konten di safe area (B4).
export const viewport: Viewport = {
  viewportFit: "cover",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="id" data-tema="gelap"
      className={`${bigShouldersDisplay.variable} ${plusJakartaSans.variable} ${courierPrime.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
